# Generated by Django 4.2.5 on 2023-12-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('centre_name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('office_image', models.ImageField(blank=True, null=True, upload_to='images/franchise/')),
                ('email', models.EmailField(max_length=254)),
                ('head_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('head_email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/profiles/teachers/')),
            ],
        ),
    ]
