# Generated by Django 4.2.5 on 2023-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_alter_franchise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
