# Generated by Django 4.2.5 on 2023-12-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_alter_franchise_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ['-id']},
        ),
    ]
