# Generated by Django 4.2.5 on 2023-09-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=1000)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Frencise',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='ALL', max_length=50),
            preserve_default=False,
        ),
    ]
