# Generated by Django 4.2.5 on 2023-12-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], default='NOT APPROVED', max_length=50),
        ),
    ]
