# Generated by Django 4.2.5 on 2023-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('UNRESOLVED', 'UNRESOVED')], default='UNRESOLVED', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False),
        ),
    ]
