# Generated by Django 4.2.5 on 2023-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_contact_alter_certificate_id_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
    ]
