# Generated by Django 4.2.5 on 2023-12-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
