# Generated by Django 4.2.5 on 2023-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_options_alter_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificates_no',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
