# Generated by Django 4.2.5 on 2023-12-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_certificate_certificates_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificates_no',
            new_name='certificate_no',
        ),
    ]
